name: CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Create jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.15"
      - name: Lint
        run: sbt scalafmt
      - name: Lint Check
        run: sbt scalafmtCheck
      - name: Build and test
        run: sbt test
        shell: bash
      - name: Create jar
        run: sbt assembly
        shell: bash
      - name: Upload jar
        id: create_release
        uses: actions/upload-artifact@v2
        with:
          name: pps-popit
          path: target/scala-2.13/*.jar
          retention-days: 1

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: actions/download-artifact@v2
      - name: Build LaTeX report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          args: '-output-format=pdf -file-line-error -synctex=1 -halt-on-error -interaction=nonstopmode -shell-escape'
          working_directory: doc/tex/report
      - name: Rename jars
        run: mv pps-popit/*.jar pps-popit/pps-popit.jar
      - name: Rename report
        run: mv doc/tex/report/*.pdf doc/tex/report/popit-report.pdf
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "0.4.0"
          prerelease: false
          title: "Scrum Sprint 4 - Release"
          files: |
            pps-popit/*.jar
            doc/tex/report/popit-report.pdf