name: CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Create jars
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.15"
      - name: Lint
        run: sbt scalafmt
      - name: Lint Check
        run: sbt scalafmtCheck
      - name: Build and test
        run: sbt test
        shell: bash
      - name: Create jar
        run: sbt assembly
        shell: bash
      - name: Upload jar
        id: create_release
        uses: actions/upload-artifact@v2
        with:
          name: pps-popit-${{ matrix.os }}
          path: target/scala-2.13/*.jar
          retention-days: 1

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Rename artifacts
        run: mv pps-popit-windows-latest/*.jar pps-popit-windows-latest/pps-popit-windows.jar
      - name: Rename artifacts
        run: mv pps-popit-ubuntu-latest/*.jar pps-popit-ubuntu-latest/pps-popit-ubuntu.jar
      - name: Rename artifacts
        run: mv pps-popit-macos-latest/*.jar pps-popit-macos-latest/pps-popit-macos.jar
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "0.3.0"
          prerelease: true
          title: "Scrum Sprint 3 - Release"
          files: |
            pps-popit-windows-latest/*.jar
            pps-popit-macos-latest/*.jar
            pps-popit-ubuntu-latest/*.jar