name: CI
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 15
          - os: windows-latest
            java: 8
          - os: windows-latest
            java: 15
          - os: macos-latest
            java: 8
          - os: macos-latest
            java: 15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Lint check with scalafmt
        run: sbt scalafmtCheck
      - name: Build and test
        run: sbt test
        shell: bash